apiVersion: v1
kind: Secret
metadata:
  name: fastify-boilerplate-secret
data:
  MONGODB_CONNECTION_STRING: "<PLACEHOLDER>"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fastify-boilerplate-job
spec:
  template:
    spec:
      containers:
      - name: fastify-boilerplate
        image: ghcr.io/<USERNAME>/fastify-boilerplate:main # TODO
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
        env:
        - name: JOB
          value: "true"
        envFrom:
        - secretRef:
            name: fastify-boilerplate-secret
      restartPolicy: OnFailure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-boilerplate-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fastify-boilerplate
  template:
    metadata:
      labels:
        app: fastify-boilerplate
    spec:
      containers:
      - name: fastify-boilerplate
        image: ghcr.io/<USERNAME>/fastify-boilerplate:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: fastify-boilerplate-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-boilerplate-service
spec:
  selector:
    app: fastify-boilerplate
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
